log_level: info,mq_bridge=info
logger: plain
ui_addr: 0.0.0.0:9090
metrics_addr: 0.0.0.0:9091
routes:
  file_to_http:
    input:
      middlewares: []
      file:
        path: input.txt
        mode: "consume"
        delete: true
    output:
      middlewares: []
      http:
        url: 127.0.0.1:3030
        tls:
          required: false
    concurrency: 1
    batch_size: 128
    commit_concurrency_limit: 4096
