#!/usr/bin/env bash
# CSV -> JSONL throughput — faucet-stream's HEADLINE benchmark (see that repo's
# BENCHMARKS.md, "CSV → JSONL Results"). Same seeded dataset faucet uses:
# data/bench.csv, 1,000,000 rows, seed 42 (id, first_name, country, amount,
# created_at, active, attributes — a mixed-type row; ~116 MiB), generated by
# gen_bench_data.py. Both tools do a one-shot full-file CSV -> local JSONL,
# one JSON object per input row (string-valued fields — matches how both
# mq-bridge's CSV reader and tap-csv emit values). 1 warmup discarded + 5 timed
# runs, median/stddev, output row-count parity check.
#
#   mq-bridge-app: copy  file://…/bench.csv?format=csv -> file://out.jsonl?format=raw
#   Meltano:       meltano run tap-csv target-jsonl  (tap-csv 1.3.2, target-jsonl 0.1.4)
#
# Prereqs:  a lean build and the tap-csv plugin installed:
#   cargo build -p mq-bridge-app --no-default-features --features bench --release
#   (cd meltano_project/bench && ../.venv/bin/meltano install extractor tap-csv)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

ROWS="${ROWS:-1000000}"
SEED="${SEED:-42}"
REPEATS="${REPEATS:-5}"
CSV="${CSV:-$HERE/data/bench.csv}"
MELTANO_PROJECT="$HERE/meltano_project/bench"
MELTANO_BIN="$HERE/meltano_project/.venv/bin/meltano"

RESULTS_DIR="${RESULTS_DIR:-$HERE/results}"
mkdir -p "$RESULTS_DIR"
OUT_CSV="$RESULTS_DIR/csv_to_jsonl.csv"
echo "tool,rows,repeats,median_elapsed_s,stddev_elapsed_s,median_rows_per_s" > "$OUT_CSV"

now() { python3 -c 'import time; print(time.time())'; }
COPY_TIMEOUT="${COPY_TIMEOUT:-900}"
OUT_FILE="${OUT_FILE:-/tmp/mqb_csv_out.jsonl}"

median_stddev() {
  python3 -c "
import statistics as s
xs=[${1}]
print(f'{s.median(xs):.3f} {s.pstdev(xs):.3f}' if len(xs) > 1 else f'{xs[0]:.3f} 0.000')
"
}

[[ -x "$BIN" ]] || { echo "binary not found at $BIN — build with --features bench --release" >&2; exit 1; }
[[ -x "$MELTANO_BIN" ]] || { echo "meltano venv not found at $MELTANO_BIN" >&2; exit 1; }

# (Re)generate the seeded CSV if missing or the wrong length (rows + header line).
want_lines=$((ROWS + 1))
have_lines="$( [[ -f "$CSV" ]] && wc -l < "$CSV" | tr -d ' ' || echo 0 )"
if [[ "$have_lines" != "$want_lines" ]]; then
  echo "generating $CSV ($ROWS rows, seed $SEED)"
  uv run --python 3.12 python3 "$HERE/gen_bench_data.py" --rows "$ROWS" --seed "$SEED" --out "$CSV"
fi

# --- mq-bridge-app copy (file CSV -> file raw JSONL) ---
copy_guarded() {
  "$BIN" copy "$@" >/dev/null 2>&1 &
  local pid=$!
  { sleep "$COPY_TIMEOUT"; kill "$pid" 2>/dev/null; } 2>/dev/null &
  local killer=$!
  disown "$killer" 2>/dev/null || true
  local rc=0; wait "$pid" 2>/dev/null || rc=$?
  kill "$killer" 2>/dev/null || true
  return "$rc"
}

from="file://${CSV}?format=csv"
to="file://${OUT_FILE}?format=raw"

echo "-- mq-bridge-app copy: warmup"
rm -f "$OUT_FILE"
copy_guarded --from "$from" --to "$to" --drain --batch-size 1024 --concurrency 1 || true

mqb_samples=()
for ((i = 1; i <= REPEATS; i++)); do
  rm -f "$OUT_FILE"
  t0="$(now)"
  copy_guarded --from "$from" --to "$to" --drain --batch-size 1024 --concurrency 1 || true
  t1="$(now)"
  landed="$( [[ -f "$OUT_FILE" ]] && wc -l < "$OUT_FILE" | tr -d ' ' || echo 0 )"
  [[ "$landed" == "$ROWS" ]] || echo "  WARNING: mq-bridge-app run $i landed ${landed} != expected ${ROWS}" >&2
  elapsed="$(python3 -c "print(f'{$t1-$t0:.6f}')")"
  echo "  mq-bridge-app run $i: ${elapsed}s"
  mqb_samples+=("$elapsed")
done
read -r mqb_median mqb_stddev <<<"$(median_stddev "${mqb_samples[*]/%/,}")"
mqb_rate="$(python3 -c "print(int($ROWS/$mqb_median))")"
printf 'mq-bridge-app,%s,%s,%s,%s,%s\n' "$ROWS" "$REPEATS" "$mqb_median" "$mqb_stddev" "$mqb_rate" | tee -a "$OUT_CSV"
rm -f "$OUT_FILE"

# --- Meltano (tap-csv -> target-jsonl) ---
run_meltano_once() {
  rm -rf "$MELTANO_PROJECT/output"
  (cd "$MELTANO_PROJECT" && "$MELTANO_BIN" run tap-csv target-jsonl) >/dev/null 2>&1
}

echo "-- meltano: warmup"
run_meltano_once || true

meltano_samples=()
for ((i = 1; i <= REPEATS; i++)); do
  t0="$(now)"
  run_meltano_once
  t1="$(now)"
  landed="$( f="$MELTANO_PROJECT/output/bench.jsonl"; [[ -f "$f" ]] && wc -l < "$f" | tr -d ' ' || echo 0 )"
  [[ "$landed" == "$ROWS" ]] || echo "  WARNING: meltano run $i landed ${landed} != expected ${ROWS}" >&2
  elapsed="$(python3 -c "print(f'{$t1-$t0:.6f}')")"
  echo "  meltano run $i: ${elapsed}s"
  meltano_samples+=("$elapsed")
done
read -r meltano_median meltano_stddev <<<"$(median_stddev "${meltano_samples[*]/%/,}")"
meltano_rate="$(python3 -c "print(int($ROWS/$meltano_median))")"
printf 'meltano,%s,%s,%s,%s,%s\n' "$ROWS" "$REPEATS" "$meltano_median" "$meltano_stddev" "$meltano_rate" | tee -a "$OUT_CSV"

echo "done -> $OUT_CSV"
