#!/usr/bin/env bash
# Seed / teardown for the ETL benchmark Postgres. Sourced by the runners and also
# usable directly:  ./seed.sh up | down | source <tbl> <bytes> <count> | dst <tbl> | cdc
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

COMPOSE="$HERE/docker-compose.postgres.yml"

pg_up() {
  docker compose -f "$COMPOSE" up -d --wait
  wait_for_pg
  echo "postgres ready at $PG_URL"
}

pg_down() { docker compose -f "$COMPOSE" down -v; }

# Populate a source table with `count` rows whose JSON payload is exactly `bytes`
# long: {"id":<n>,"pad":"xxx…"} rpad-ded to the target byte length.
seed_source() {
  local tbl="$1" bytes="$2" count="$3"
  psql_q <<SQL
CREATE TABLE IF NOT EXISTS ${tbl} (id bigserial PRIMARY KEY, payload text);
TRUNCATE ${tbl} RESTART IDENTITY;
INSERT INTO ${tbl} (payload)
SELECT rpad(format('{"id":%s,"pad":"', g), ${bytes} - 2, 'x') || '"}'
FROM generate_series(1, ${count}) AS g;
SQL
  local n len
  n="$(psql_q -c "SELECT count(*) FROM ${tbl};")"
  len="$(psql_q -c "SELECT length(payload) FROM ${tbl} LIMIT 1;")"
  echo "seeded ${tbl}: ${n} rows, payload length ${len} bytes"
}

# Fresh empty destination table for the sqlx sink.
reset_dst() {
  local tbl="$1"
  psql_q <<SQL
CREATE TABLE IF NOT EXISTS ${tbl} (id bigserial PRIMARY KEY, payload text);
TRUNCATE ${tbl} RESTART IDENTITY;
SQL
  echo "reset ${tbl} (empty)"
}

# CDC captured table + publication. Drops any leftover replication slot first so
# a permanent slot from a previous run can't shadow this one (a lingering/again-
# dropped slot makes streaming fail with "slot does not exist"). The endpoint then
# recreates the slot on startup (create_slot: true).
seed_cdc() {
  local tbl="${1:-cdc_src}" pub="${2:-mqb_pub}" slot="${3:-mqb_slot}"
  psql_q <<SQL
SELECT pg_drop_replication_slot(slot_name) FROM pg_replication_slots WHERE slot_name = '${slot}';
DROP PUBLICATION IF EXISTS ${pub};
DROP TABLE IF EXISTS ${tbl};
CREATE TABLE ${tbl} (id bigserial PRIMARY KEY, payload text, ins_ts double precision);
ALTER TABLE ${tbl} REPLICA IDENTITY FULL;
CREATE PUBLICATION ${pub} FOR TABLE ${tbl};
SQL
  echo "cdc ready: table ${tbl}, publication ${pub}"
}

# Seed the `bench` table used by the Meltano comparison (scenario 5): schema
# id/first_name/country/amount/created_at/active/attributes, loaded via
# `\copy`/COPY FROM STDIN from a CSV generated by gen_bench_data.py (seeded,
# deterministic for a given --seed/--rows).
seed_bench() {
  local rows="${1:-1000000}" seed="${2:-42}"
  local csv="$HERE/data/bench.csv"
  mkdir -p "$HERE/data"
  uv run --python 3.12 python3 "$HERE/gen_bench_data.py" --rows "$rows" --seed "$seed" --out "$csv"
  psql_q <<SQL
DROP TABLE IF EXISTS bench;
CREATE TABLE bench (
  id bigint, first_name text, country text, amount double precision,
  created_at timestamptz, active boolean, attributes jsonb);
SQL
  # COPY ... FROM STDIN (protocol-level, not the client-side \copy meta-command)
  # so loading works whether psql runs on the host or inside the compose
  # container via `docker exec -i` (lib.sh's psql_q fallback).
  if command -v psql >/dev/null 2>&1; then
    psql "$PG_URL" -v ON_ERROR_STOP=1 -qtA -c "\copy bench FROM '${csv}' WITH (FORMAT csv, HEADER true);"
  else
    docker exec -i "$PG_CONTAINER" psql -U "$PGUSER" -d "$PGDATABASE" -v ON_ERROR_STOP=1 -qtA \
      -c "COPY bench FROM STDIN WITH (FORMAT csv, HEADER true);" < "$csv"
  fi
  local n
  n="$(psql_q -c "SELECT count(*) FROM bench;")"
  echo "seeded bench: ${n} rows (seed=${seed})"
}

case "${1:-}" in
  up)     pg_up ;;
  down)   pg_down ;;
  source) seed_source "$2" "$3" "$4" ;;
  dst)    reset_dst "$2" ;;
  cdc)    seed_cdc "${2:-cdc_src}" "${3:-mqb_pub}" "${4:-mqb_slot}" ;;
  bench)  seed_bench "${2:-1000000}" "${3:-42}" ;;
  "")     : ;;  # sourced, not invoked
  *)      echo "usage: $0 up|down|source <tbl> <bytes> <count>|dst <tbl>|cdc [tbl] [pub] [slot]|bench [rows] [seed]" >&2; exit 2 ;;
esac
