#!/usr/bin/env bash
#
# sync-engine-docs.sh — vendor the canonical engine docs into the book.
#
# Single source of truth: the .md files listed below live in the mq-bridge
# ENGINE repo and are the authoritative reference. This script copies them into
# dev/docs/engine/ so the book can render them, injecting a read-only header and
# rewriting cross-links so they resolve inside the book. The copies are build
# artifacts (git-ignored) — never edit them here; edit the source in mq-bridge.
#
# Run it from the repo root before `mdbook build dev/docs` (see dev/docs/README.md). Re-run it whenever the
# engine docs change.
#
set -euo pipefail

ENGINE_RAW_BASE="https://github.com/marcomq/mq-bridge/blob/main"

# Resolve paths relative to this script so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/engine"

# Location of the engine repo. Defaults to a sibling of the app repo
# (repo-root/../mq-bridge); override with ENGINE_REPO=/path/to/mq-bridge.
ENGINE_REPO="${ENGINE_REPO:-$SCRIPT_DIR/../../../mq-bridge}"

# source-file-in-engine  ->  vendored-basename-in-book
#   Keep the vendored basename lower-case; SUMMARY.md links to it.
FILES=(
  "REFERENCE.md:reference.md"
  "CONFIGURATION.md:configuration.md"
  "ARCHITECTURE.md:architecture.md"
)

if [[ ! -d "$ENGINE_REPO" ]]; then
  echo "error: engine repo not found at '$ENGINE_REPO'." >&2
  echo "       set ENGINE_REPO=/path/to/mq-bridge and re-run." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

for entry in "${FILES[@]}"; do
  src_name="${entry%%:*}"
  dst_name="${entry##*:}"
  src="$ENGINE_REPO/$src_name"
  dst="$OUT_DIR/$dst_name"

  if [[ ! -f "$src" ]]; then
    echo "error: source '$src' does not exist." >&2
    exit 1
  fi

  # A previous run left the artifact read-only; restore write access so this run can
  # truncate it.
  if [[ -e "$dst" ]]; then
    chmod u+w "$dst"
  fi

  {
    # Hidden read-only header — invisible in the rendered page, loud in the source.
    printf '<!--\n'
    printf '  AUTO-GENERATED — DO NOT EDIT THIS FILE.\n'
    printf '  Source of truth: mq-bridge repo /%s\n' "$src_name"
    printf '  Vendored into the book by dev/docs/sync-engine-docs.sh. Edit the source, then re-run the script.\n'
    printf -- '-->\n\n'
    cat "$src"
  } \
  | perl -pe '
      # Rewrite cross-links between the vendored engine docs to their book paths.
      s{\]\(REFERENCE\.md}{](reference.md}g;
      s{\]\(CONFIGURATION\.md}{](configuration.md}g;
      s{\]\(ARCHITECTURE\.md}{](architecture.md}g;
    ' \
  | perl -pe '
      # Rewrite links to engine files we do NOT vendor to their GitHub source,
      # so the book has no broken relative links.
      s{\]\(README\.md}{]('"$ENGINE_RAW_BASE"'/README.md}g;
      s{\]\(CONTRIBUTING\.md}{]('"$ENGINE_RAW_BASE"'/CONTRIBUTING.md}g;
      s{\]\(LICENSE}{]('"$ENGINE_RAW_BASE"'/LICENSE}g;
      s{\]\(mq-bridge\.schema\.json}{]('"$ENGINE_RAW_BASE"'/mq-bridge.schema.json}g;
      s{\]\(benches/}{]('"$ENGINE_RAW_BASE"'/benches/}g;
    ' \
  > "$dst"

  # Make the artifact read-only so an accidental edit is caught by the OS too.
  chmod a-w "$dst" 2>/dev/null || true
  echo "vendored $src_name -> engine/$dst_name"
done

echo "done. $(( ${#FILES[@]} )) engine doc(s) synced into engine/."
