#!/usr/bin/env bash
#
# sync-engine-docs.sh — vendor the canonical engine docs into the book.
#
# Single source of truth: the .md files listed below live in the mq-bridge
# ENGINE repo and are the authoritative reference. This script copies them into
# dev/docs/engine/ so the book can render them, injecting a read-only header and
# rewriting cross-links so they resolve inside the book. The copies are build
# artifacts (git-ignored) — never edit them here; edit the source in mq-bridge.
#
# Run it from the repo root before `mdbook build dev/docs` (see dev/docs/README.md). Re-run it whenever the
# engine docs change.
#
set -euo pipefail

ENGINE_RAW_BASE="https://github.com/marcomq/mq-bridge/blob/main"

# Resolve paths relative to this script so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/engine"

# Location of the engine repo. Defaults to a sibling of the app repo
# (repo-root/../mq-bridge); override with ENGINE_REPO=/path/to/mq-bridge.
ENGINE_REPO="${ENGINE_REPO:-$SCRIPT_DIR/../../../mq-bridge}"

# The engine docs live in mq-bridge/docs/.
ENGINE_DOCS="$ENGINE_REPO/docs"

# source-file-in-engine-docs  ->  vendored-basename-in-book
#   Keep the vendored basename lower-case; SUMMARY.md links to it.
FILES=(
  "REFERENCE.md:reference.md"
  "CONFIGURATION.md:configuration.md"
  "ARCHITECTURE.md:architecture.md"
  "DELIVERY.md:delivery.md"
  "EXTENDING.md:extending.md"
  "PLUGINS.md:plugins.md"
)

if [[ ! -d "$ENGINE_DOCS" ]]; then
  echo "error: engine docs not found at '$ENGINE_DOCS'." >&2
  echo "       set ENGINE_REPO=/path/to/mq-bridge and re-run." >&2
  exit 1
fi

# Cross-link rewrites, derived from FILES so adding a doc above is the only edit needed.
CROSSLINKS=""
for entry in "${FILES[@]}"; do
  src_name="${entry%%:*}"
  CROSSLINKS+="s{\]\(${src_name/./\\.}}{](${entry##*:}}g;"
done

mkdir -p "$OUT_DIR"

for entry in "${FILES[@]}"; do
  src_name="${entry%%:*}"
  dst_name="${entry##*:}"
  src="$ENGINE_DOCS/$src_name"
  dst="$OUT_DIR/$dst_name"

  if [[ ! -f "$src" ]]; then
    echo "error: source '$src' does not exist." >&2
    exit 1
  fi

  # A previous run left the artifact read-only; restore write access so this run can
  # truncate it.
  if [[ -e "$dst" ]]; then
    chmod u+w "$dst"
  fi

  {
    # Hidden read-only header — invisible in the rendered page, loud in the source.
    printf '<!--\n'
    printf '  AUTO-GENERATED — DO NOT EDIT THIS FILE.\n'
    printf '  Source of truth: mq-bridge repo /docs/%s\n' "$src_name"
    printf '  Vendored into the book by dev/docs/sync-engine-docs.sh. Edit the source, then re-run the script.\n'
    printf -- '-->\n\n'
    cat "$src"
  } \
  | perl -pe "$CROSSLINKS" \
  | perl -pe '
      # Anything outside docs/ (../README.md, ../CONTRIBUTING.md, ../benches/, …) is not
      # vendored — point it at the GitHub source so the book has no broken relative links.
      s{\]\(\.\./}{]('"$ENGINE_RAW_BASE"'/}g;
    ' \
  > "$dst"

  # Make the artifact read-only so an accidental edit is caught by the OS too.
  chmod a-w "$dst" 2>/dev/null || true
  echo "vendored $src_name -> engine/$dst_name"
done

echo "done. $(( ${#FILES[@]} )) engine doc(s) synced into engine/."
