# Exposes an HTTP endpoint and respond static content
# Used for performance tests

log_level: info,mq_bridge=info
logger: plain
metrics_addr: 0.0.0.0:9090 # prometheus compatible metrics
ui_addr: 0.0.0.0:9091  # you should delete the UI on production
routes:
  file_to_http:
    input:
      file:
        path: input.log
        mode: consume
        delete: true
    output:
      middlewares:
        - retry:
            max_attempts: 10
            initial_interval_ms: 100
            max_interval_ms: 2000
        - dlq:
            endpoint:
              file:
                path: error.log
      http: # Use environment variable substitution with a default value
        url: ${TARGET_HOST:-host.docker.internal}:3030
        tls:
          required: false
    concurrency: 1
    batch_size: 1024
    commit_concurrency_limit: 4096
