#!/usr/bin/env bash
# Render the Homebrew formula (CLI) and cask (desktop UI) for a given release,
# with real sha256s pulled from the published GitHub release assets, into
# <outdir>/Formula/mq-bridge-app.rb and <outdir>/Casks/mq-bridge.rb.
#
# This is the ONE place the formula/cask text lives. Both the release CI job and
# the one-time tap bootstrap call it, so there is nothing to keep in sync and no
# committed .rb to drift. It does not push anything — the caller copies the
# output into the tap repo (marcomq/homebrew-tap) and commits.
#
# Usage:
#   render.sh <version> [repo] [outdir]
#     version   release tag, e.g. 0.2.8   (required)
#     repo      owner/name  (default: marcomq/mq-bridge-app)
#     outdir    where to write Formula/ and Casks/ (default: ./out)
set -euo pipefail

VERSION="${1:?usage: render.sh <version> [repo] [outdir]}"
REPO="${2:-marcomq/mq-bridge-app}"
OUTDIR="${3:-out}"
BASE="https://github.com/${REPO}/releases/download/${VERSION}"
# The download URL path segment is the release TAG (VERSION), but the Tauri
# bundle filenames carry the cargo version with no leading 'v'. Keep them
# separate so a v-prefixed tag (e.g. v0.2.9) still resolves the uploaded .dmg.
CARGO_VERSION="${VERSION#v}"

# Portable sha256 of a released asset, streamed (no temp file needed).
sha() {
  local sum
  if command -v sha256sum >/dev/null 2>&1; then sum="sha256sum"; else sum="shasum -a 256"; fi
  curl -fsSL "${BASE}/$1" | $sum | cut -d' ' -f1
}

echo "resolving checksums for ${REPO} ${VERSION} ..." >&2
MAC_ARM="$(sha "mq-bridge-cli-aarch64-apple-darwin.tar.gz")"
LINUX_X64="$(sha "mq-bridge-cli-x86_64-unknown-linux-gnu.tar.gz")"
LINUX_ARM64="$(sha "mq-bridge-cli-aarch64-unknown-linux-gnu.tar.gz")"
DMG="$(sha "mq-bridge_${CARGO_VERSION}_aarch64.dmg")"

mkdir -p "${OUTDIR}/Formula" "${OUTDIR}/Casks"

# --- CLI / MCP server formula -------------------------------------------------
cat > "${OUTDIR}/Formula/mq-bridge-app.rb" <<RUBY
# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh — do not edit by hand.
class MqBridgeApp < Formula
  desc "Universal, protocol-agnostic message and data bridge (CLI + MCP server)"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/mq-bridge-cli-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/mq-bridge-cli-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X64}"
    end
    on_arm do
      url "${BASE}/mq-bridge-cli-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    bin.install "mq-bridge-cli" => "mq-bridge-app"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mq-bridge-app --version")
  end
end
RUBY

# --- Desktop UI cask (macOS arm64 Tauri bundle) -------------------------------
cat > "${OUTDIR}/Casks/mq-bridge.rb" <<RUBY
# Generated by packaging/homebrew/render.sh — do not edit by hand.
cask "mq-bridge" do
  version "${VERSION}"
  sha256 "${DMG}"

  url "${BASE}/mq-bridge_${CARGO_VERSION}_aarch64.dmg"
  name "mq-bridge"
  desc "Desktop UI for mq-bridge — universal message and data bridge"
  homepage "https://github.com/${REPO}"

  depends_on arch: :arm64

  app "mq-bridge.app"

  zap trash: [
    "~/Library/Application Support/com.marcomq.mqbridgeapp",
    "~/Library/Caches/com.marcomq.mqbridgeapp",
    "~/Library/Preferences/com.marcomq.mqbridgeapp.plist",
    "~/Library/Saved Application State/com.marcomq.mqbridgeapp.savedState",
  ]
end
RUBY

echo "wrote ${OUTDIR}/Formula/mq-bridge-app.rb and ${OUTDIR}/Casks/mq-bridge.rb" >&2
